グラフのサイズと表のカラーを追加
LLstream/atcoder-multi-charts pull request #11
Opened 2024-12-04 13:07 UTC by zerozero-0-0

2024-12-05 02:40 UTC, LLstream approved these changes
いいと思います！ありがとう！

2024-12-05 12:40 UTC, takashin9 approved these changes
いいと思います

2024-12-05 12:55 UTC, takashin9 requested changes
と思ったんだけど、global.cssとpage.module.cssとlayout.tsxのデザインに関係する部分を全削除してから、style.cssを新しく作るんじゃなくて、page.module.cssにpage.tsxのデザインの内容を書く形にしたいかも

2024-12-05 13:00 UTC, takashin9 commented
@zerozero-0-0 とりあえず、元のデザインの部分は消したので、 page.module.cssにデザインを書く感じにお願いします

2024-12-05 13:16 UTC, zerozero-0-0 commented
了解です

2024年12月5日(木) 22:01 takashin9 ***@***.***>:

> @zerozero-0-0 <https://github.com/zerozero-0-0> とりあえず、元のデザインの部分は消したので、
> page.module.cssにデザインを書く感じにお願いします
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LLstream/atcoder-multi-charts/pull/11#issuecomment-2520263973>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BH5J2KJ3RSL54YUB5IWEO532EBFBPAVCNFSM6AAAAABTAEE4FWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRQGI3DGOJXGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-09 08:30 UTC, zerozero-0-0 commented
遅れてすみません
css変更したので確認お願いします

2024-12-09 08:40 UTC, takashin9 approved these changes
ざっと見た感じいいと思います。style.cssは消しときます。

2024-12-09 09:18 UTC, LLstream approved these changes

2024-12-09 09:19 UTC, merged